# This is a sample plugin.yml
# For more information refer to http://wiki.bukkit.org/Plugin_YAML
main: edu.unca.smmattic.Plug1.Plug1
name: ${project.name}
version: ${project.version}
author: SampleAuthor
description: ${project.description}
commands:
  sample:
    description: set the sample message
    usage: /<command> message
    permission: sample.message
permissions:
  sample.*:
    description: gives all permissions of the SamplePlugin
    default: op
    children:
      sample.message:
        description: gives permission to set the sample message using the sample command
  dying:
    description: Gives the player aid
    usage: /dying - gives player a bed, 3 loaves of bread, an iron sword and 3 torches
permissions:
   dying.*:
    description: gives player aid
    default: true